version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: TO_ADMIN
      MYSQL_DATABASE: observer
      MYSQL_USER: TO_USER
      MYSQL_PASSWORD: TO_USER_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
