version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: observer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: to_admin
      MYSQL_DATABASE: observer
      MYSQL_USER: to_user
      MYSQL_PASSWORD: to_user_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
