server:
  host: 0.0.0.0
  port: 8000

database:
  host: 127.0.0.1
  port: 3306
  environment:
    pool_pre_ping: True
    pool_recycle: 300
    pool_size: 5
    max_overflow: 0
    MYSQL_ROOT_PASSWORD: TO_ADMIN
    MYSQL_DATABASE: observer
    MYSQL_USER: TO_USER
    MYSQL_PASSWORD: TO_USER_PASSWORD

JWT_SECRET: 13415ESASDA4SADNASNDOJOF6SDA46S5AF487HTS6RTH84
JWT_ALGORITHM: HS256
ACCESS_TOKEN_EXPIRE_MINUTES: 60




